Vault enhancements
cyberark/CYBRHardeningCheck pull request #35
Opened 2021-04-13 12:54 UTC by AssafMiron

### What does this PR do?
- Adding more hardening checks for the Vault
- Fixing some issues

### What ticket does this PR close?
Resolves #7 
Resolves #9 
Might resolve #8

### Checklists
Run a test on a VM vault (to reproduce the Ethernet issue)
Run a test on a non hardened, default vault (to check the FW rules and Vault Certificate)

#### Documentation
- [ ] Docs (e.g. `README`s) were updated in this PR, and/or there is a follow-on issue to update docs

2021-04-13 12:58 UTC, AssafMiron commented
@itsmegb , @NathTheDude would be great if you can verify this new change as it should solve some of the enhancements and a bug that you identified for the Vault
Thanks!

2021-04-16 08:42 UTC, itsmegb commented
This all looks good to me! Potentially an issue with the Firewall rule checking, the verbose logs report that i have 1 non-standard rule in my dbparm.ini but also states that i have 3 non-standard FW rules configured. Looking at the FW rules, i have 2 manual rules defined.
Would it be a good idea to clarify this a bit further?

2021-04-16 08:51 UTC, itsmegb requested changes
This all looks good to me! Potentially an issue with the Firewall rule checking, the verbose logs report that i have 1 non-standard rule in my dbparm.ini but also states that i have 3 non-standard FW rules configured. Looking at the FW rules, i have 2 manual rules defined.
Would it be a good idea to clarify this a bit further?

2021-04-18 08:25 UTC, AssafMiron commented
Thanks @itsmegb 
I added also the ICMP rules that were missing in the DBParm.ini (these are configured behind the scenes and not as part of the file
So I suspect this is where the confusion might lay
ley me know if now it makes more sense

Thanks,
Assaf

2021-04-18 19:03 UTC, AssafMiron commented
@itsmegb I added another change to the Static IP check to handle the special case of NIC teaming
We actually check if there is teaming configured in the NIC hardening check, so I  used that to check the Team name when checking for static IP configuration
If you still have your environment with NIC teaming configured, let me know if that works

Thanks,
Assaf

2021-04-19 14:18 UTC, AssafMiron commented
@itsmegb after our talk (and a few debugging tries) I figured out the issue and updated the script
I checked it on my lab - please verify at yours

2021-04-22 10:05 UTC, itsmegb requested changes
There appears to be a line that breaks the script, in the new Vault_KeysProtection function.

2021-04-22 10:46 UTC, AssafMiron commented on CYBRHardeningCheck/Vault/VaultHardeningSteps.psm1
> +			Write-LogMessage -Type Verbose -Msg "Found the following Keys paths: $($KeysList -join `n)"
Sorry about that, missed it somehow
Will push a new commit to fix it

2021-04-22 11:14 UTC, itsmegb commented on CYBRHardeningCheck/Vault/VaultHardeningSteps.psm1
> +			Write-LogMessage -Type Verbose -Msg "Found the following Keys paths: $($KeysList -join `n)"
Excellent, that is now working as expected.

2021-04-22 11:37 UTC, AssafMiron commented on CYBRHardeningCheck/Vault/VaultHardeningSteps.psm1
> +			If(Test-Path $RecoveryKey)
I added more logging to verify
On my env I don't have it on the machine and I can see it in the log

2021-04-22 11:38 UTC, AssafMiron commented on CYBRHardeningCheck/Vault/VaultHardeningSteps.psm1
> +					If((Compare-AmountOfUserPermissions -Path $path -amount 2 -outStatus ([ref]$myRef)) -ne "Good")
I think that Creator owner is not really a valid user that we would want
Maybe we should push customers to remove it
WDYT?

2021-04-22 12:34 UTC, itsmegb commented on CYBRHardeningCheck/Vault/VaultHardeningSteps.psm1
> +			If(Test-Path $RecoveryKey)
So it looks like the value of $RecoveryKey includes the "RecoveryPrvKey=" part, so the test is failing as it isn't a valid location on disk.

I think just splitting the value returned by the match _should_ make the test work correctly.

2021-04-22 12:55 UTC, itsmegb commented on CYBRHardeningCheck/Vault/VaultHardeningSteps.psm1
> +					If((Compare-AmountOfUserPermissions -Path $path -amount 2 -outStatus ([ref]$myRef)) -ne "Good")
Removing CREATOR OWNER doesn't seem to effect the Vault (in my _very_ limited testing).

It does appear to be an inherited permission, so i'm not sure whether it is required or not?

2021-04-22 18:08 UTC, AssafMiron commented on CYBRHardeningCheck/Vault/VaultHardeningSteps.psm1
> +			If(Test-Path $RecoveryKey)
Ahhh... you are correct and I can see that it was missing.
Adding now the split to have the real path

2021-04-22 18:30 UTC, AssafMiron commented on CYBRHardeningCheck/Vault/VaultHardeningSteps.psm1
> +					If((Compare-AmountOfUserPermissions -Path $path -amount 2 -outStatus ([ref]$myRef)) -ne "Good")
Looking online a bit I see a lot of places saying to remove the Creator Owner permission
So I think it should be OK

2021-05-30 19:25 UTC, merged